import asyncio

import pytest
from loguru import logger
from syft_event import SyftEvents

from syft_rds.client.rds_client import RDSClient, init_session
from syft_rds.server.app import create_app
from tests.conftest import DS_PATH
from tests.e2e.conftest import Client, E2EContext, Server
from tests.utils import create_dataset


def deployment_config():
    server = Server()
    return {
        "e2e_name": "full_flow",
        "server": server,
        "clients": [
            Client(name="data_owner", server_port=server.port),
            Client(name="data_scientist", server_port=server.port),
        ],
    }


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "e2e_context", [deployment_config()], indirect=True, ids=["deployment"]
)
async def test_e2e_full_flow(e2e_context: E2EContext):
    logger.info(f"Starting E2E '{e2e_context.e2e_name}'")
    e2e_context.reset_test_dir()
    await e2e_context.start_all()
    await asyncio.sleep(3)

    data_scientist = None
    data_owner = None
    for client in e2e_context.clients:
        if client.name == "data_owner":
            data_owner = client
        if client.name == "data_scientist":
            data_scientist = client

    rds_server: SyftEvents = create_app(data_owner)
    do_rds_client: RDSClient = init_session(
        host=data_owner.email,
        syftbox_client_config_path=data_owner.config_path,
        mock_server=rds_server,
    )
    ds_rds_client: RDSClient = init_session(
        host=data_owner.email,
        syftbox_client_config_path=data_scientist.config_path,
        mock_server=rds_server,
    )
    assert do_rds_client.is_admin
    assert not ds_rds_client.is_admin
    logger.info(
        f"Clients initialized. DO email: {do_rds_client.email}. DS email: {ds_rds_client.email}"
    )

    dataset_name = "dataset-1"
    try:
        create_dataset(do_rds_client, dataset_name)
    except Exception as e:
        logger.error(f"Error creating dataset: {e}")
    await asyncio.sleep(3)  # wait for the dataset to be synced
    assert len(do_rds_client.dataset.get_all()) == 1

    dataset = ds_rds_client.dataset.get(name=dataset_name)
    dataset.describe()
    with pytest.raises(Exception) as excinfo:
        dataset.get_private_path()
        logger.error(f"DS tries to access the private data raised {excinfo}")

    job = ds_rds_client.job.submit(
        user_code_path=DS_PATH / "ds.py", dataset_name=dataset.name
    )
    await asyncio.sleep(3)

    jobs = ds_rds_client.job.get_all()
    assert len(jobs) == 1

    res_job = do_rds_client.run_private(job)
    res_path, _ = do_rds_client.job.share_results(res_job)
    assert res_path.exists()

    job = ds_rds_client.job.get_all()[-1]
    assert job.output_url == res_job.output_url
    assert job._client.email == data_scientist.email

    await asyncio.sleep(3)
    ds_job_output_path = job.get_output_path()
    logger.info(f"{ds_job_output_path = }")
    assert ds_job_output_path.exists()
